-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["ql_the_forest_ancient_ruins_1"] = {{ name = "other", tiles = {"ql_the_forest_ancient_ruins_5", "ql_the_forest_ancient_ruins_5"} }}
overlayMap["ql_the_forest_nature_0"] = {{ name = "other", tiles = {"ql_the_forest_nature_1", "ql_the_forest_nature_1"} }}
overlayMap["ql_the_forest_nature_2"] = {{ name = "other", tiles = {"ql_the_forest_nature_3", "ql_the_forest_nature_3"} }}
overlayMap["ql_the_forest_nature_4"] = {{ name = "other", tiles = {"ql_the_forest_nature_5", "ql_the_forest_nature_5"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
